### ISSUE TITLE
Ethereum oracle event ordering issues

### ISSUE THREAD

**Issue by jtremback** [althea-net/cosmos-gravity-bridge#119]
Thanks to @balasan for pointing this out.

It's important that Ethereum events are played into the Cosmos state in the exact order they were emitted on Ethereum. Double-spends could result otherwise.

We put an "event nonce" on events emitted from the Ethereum contract. If events are observed with a non-contiguous event nonce, we know there's a problem. We check for this in two places. When an individual validator submits a claim about an event, we error if their previously submitted claim does not have a nonce exactly 1 lower than the current claim. This allows honest validators to correct mis-orderings caused by network delay and other issues.

However, a validator can submit any event under a certain nonce. A malicious validator could vote for a different event with nonce 2, then vote for the same event with nonce 3 as everyone else. This could cause event 3 to pass the threshold before event 2. This could probably also happen naturally, without malicious validators, although it seems unlikely.

The good news is that we also check that nonces are contiguous when we mark an event "observed", and alter the Cosmos state according to it. Non-contiguous event nonces resulting from the scenario described above will currently cause the module to panic. No events can be applied to the state non-contiguously. The bad news is that a panic causes the chain to halt.

To fix this, we should use a more refined strategy of applying events to state. 

- Events will be submitted as claims and add their validator's vote to an attestation as they currently do
- Nothing will happen when a validator's claim pushes an event over the threshold.
- Instead, there will be a process every endBlock that looks at all attestations currently being voted on
  - It will try to apply their events to the Cosmos state, while maintaining contiguousness
  - e.g. If event 1 and 2 are over the threshold, but 3 is below the threshold, it will apply 1 and 2
  - Next endBlock, if 4, 5, and 6 are over the threshold, it will not apply any events
  - Next endBlock, if 3 finally goes over the threshold, it will apply 3, 4, 5, and 6

This will ensure events are always observed in order, without chain halts

**Comment by jtremback** [comment]
@jkilpatr @jackzampolin

**Comment by jkilpatr** [comment]
seems like this is done in the current code @jtremback  can you please review?

**Comment by jtremback** [comment]
> seems like this is done in the current code @jtremback can you please review?

Nope

**Comment by jtremback** [comment]
This was solved by the endblocker attestation tallying code.
