### ISSUE TITLE
Slashing

### ISSUE THREAD

**Issue by jtremback** [althea-net/cosmos-gravity-bridge#121]
## Ethereum oracle
- Validators not voting for attestations which are observed should be slashed for a liveness fault
  - There needs to be a buffer period after an attestation's observation for all the validators to get their votes in, since otherwise ~1/3 of the validation power would be slashed for liveness after each attestation.
  - How long is too long for this buffer period? If it is too long, validators may not be properly incentivized for liveness, and the bridge will have an unacceptable delay.
- OPEN QUESTION: Should validators who sign over a *different* attestation than the one that is observed by at least 2/3s of the validation power for a given event nonce get a more severe slashing than liveness? The effect of this would be to punish validators on the losing side of a disagreement about what the Ethereum state is. I'm not sure this is a good idea, since it does not exactly disincentivize falsifications of the Ethereum state, just *unsuccessful* falsifications. It could also result slashing of innocent validators in the case of an Ethereum fork.
  - Related: What happens after an Ethereum fault which results in, for example, the event nonce in Peggy.sol being rolled back so that no validator can submit a valid claim? In this case, no more claims will be submittable and the bridge will stop. This is not necessarily a bad thing, and can be fixed by a patch for the Eth signer which adds a fixed integer to each event nonce, allowing events to be submitted again.

### Liveness slashing
We can start thinking about slashing here with a simple rule: if a batch or a valset update has been created by the Peggy module, it MUST be signed by each validator's Eth signer. This is because if a validator participates in the consensus process to create a batch or a valset update, and then runs an Eth signer that does not sign it, this is a clear inconsistency.

### Fraudulent signatures
Another scenario is one where a fraudulent valset or batch is signed, in an attempt by malicious validators to rob the bridge. We will need an evidence mechanism for this. We should slash for any evidence of a fraudulent signature, not just ones that have been successfully submitted to Ethereum. We should slash hard for fraudulent signatures, probably with an equivalent penalty to double signing.

What constitutes a fraudulent signature? A signature over any batch or valset which was never produced by the peggy module. Naively, this would require us to store every batch and valset ever created by the peggy module. We can trivially reduce this storage size by storing only hashes. We could probably reduce it further using a merkel tree or some kind of other fancy fraud proof. We may also not need to store every batch and valset ever, we may be able to stop slashing for batches or valsets from long enough ago.

**Comment by jtremback** [comment]
Let's say that a set of evil validators wants to steal from the bridge. They offer 0% commissions and soon have 2/3's of the Cosmos chain's tokens delegated to them. They now hold private keys controlling the funds in the bridge. They steal the funds with a fraudulent batch, and get slashed hard on the Cosmos chain, but most of the tokens that get slashed belong to their delegators. 

I believe this scenario is impossible to guard against, and it shouldn't be a goal for us. Even if Peggy.sol had perfect knowledge of the Cosmos chain, this scenario could still take place because it is also a viable attack on Cosmos, and perhaps any PoS blockchain. The attacker would just change the rules of the Cosmos chain and Peggy.sol would have to go along with it.

However, there could be another scenario. Perhaps the evil validators could just refuse to sign any valset updates, unbond their own tokens, and wait until the unbonding period was up. Then they could sign whatever they wanted with none of their tokens at stake. To avoid this scenario, we need to make sure that being slashing for downtime for a whole unbonding period is as expensive as being slashed for a fraudulent signature.

**Comment by jkilpatr** [comment]
After a meeting we have agreed on a set of two slashing conditions that should properly slash malicious participants if they try and steal funds from the bridge.

1) A validator will be jailed (for downtime) if they fail to sign validator set updates or transaction batches produces by the chain within a reasonable amount of time (lets say 50 Cosmos blocks)

2) Once a validator has been jailed in order to retrieve their stake they must submit a valid valset update and transaction batch (if applicable) or face the total loss of all their stake (including the stake of delegators) if they do not do so within a period less than the unbonding period (perhaps the unbonding period minus one day). This will force someone attacking the bridge to either lose their control over the bridge or lose all their stake.

**Comment by jtremback** [comment]
Don't forget the Ethereum oracle slashing condition as well:

Validators not voting for attestations which are observed should be slashed for a liveness fault
- There needs to be a buffer period after an attestation's observation for all the validators to get their votes in, since otherwise ~1/3 of the validation power would be slashed for liveness after each attestation.

**Comment by jtremback** [comment]
Mostly implemented, there is ongoing discussion but this issue is dead
