### ISSUE TITLE
Block timeout for batches

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/cosmos-gravity-bridge#138]
We should have a timeout for batches on blocks that allows us to release transactions back into the batch pool after a given amount of time.

- [x] Add timeout blocks as a paramater to the batch contract call
- [x] Check that block is not greater than timeout blocks on submission
- [x] Test the above changes
- [x] Have oracle events (ValsetUpdate and BatchExecuted) include a block height
- [x] When these oracle events come in and are confirmed with a higher block height than the timeout of an active batch go and release the transactions in those batches
- [ ] Add in UI endpoints so that UX can see transactions in the pool (waiting to be included in a batch)
- [x] Add Msg that allows a user to remove their transaction from the transaction pool so long as it is not in a batch

User story:
Lee wants to send his FooToken from Comsos to Ethereum, no one else is using FooToken at all, so its the only transaction in the pool for that token. For some reason a relayer requests it be placed into a batch (probably maliciously) and never relays it. That batch is signed and Lee's tokens are now stuck. But since batches timeout after 24 hours worth of blocks Lee will eventually see his funds return to the pool where he can retrieve them.

Question: Do we want funds to return to the pool or just return to the user? If they return to the pool there's a chance that when a batch times out a new more profitable batch is immediately made and sent across including the best of the transactions in the pool and those previously in the batch. On the other hand there's some risk of a spam attack where you lock up someone's tokens forever by having a bot send MsgRequestBatch for that token type every time the last batch times out without being submitted.

**Comment by jkilpatr** [comment]
As a quick aside I think this is about a days worth of work and I'll be happy to slide it in whenever it won't cause conflicts. So not right now as @jackzampolin  has a big set of PRs coming.

**Comment by jackzampolin** [comment]
If we return to the pool would this be basically an automatic retry?

**Comment by jtremback** [comment]
@jackzampolin In scenarios where we have an inactive token type, where not a lot of txs are going in and so no new batches are getting submitted, this will free unprofitable txs and put them back in the tx pool. On active token types it will not have any effect.

When a tx goes back into the tx pool, after being invalidated by a batch with a higher nonce, OR with this new timeout, it can be included in a new batch that is more profitable. Or it might not be if it is just not profitable enough. In this case the user can cancel it and get the tokens back, then retry with a higher fee.

**Comment by jtremback** [comment]
This is really off topic, but we could even let users add higher fees to transactions that are in live batches without waiting for the batch to be invalidated either by a timeout or by a higher nonce.

I'm definitely not recommending this, but it would involve totally re-engineering the fee payouts to happen on the Cosmos side. We would add a new event to the contract which would contain msg.sender for a successfully submitted batch. The relayer would then get the fee paid on the cosmos side.

Then users would be able to send a Cosmos transaction at any time that would raise the fee they were offering for a tx.

**Comment by jtremback** [comment]
Done
