### ISSUE TITLE
Add an API to see who has not voted on a given batch or validator set

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/cosmos-gravity-bridge#146]
Currently the endpoints for getting batch confirms or valset confirms only associate the voter with an ethereum key, they don't tell you who the validator is that has or has not voted. 

This isn't important for actual functionality but is very important to debug a situation where validators are not running their orchestrators.

Although I guess in theory this may become moot when staking as complete since people will be kicked out of the set for not submitting signatures.

**Comment by jtremback** [comment]
This was implemented in the relayer itself.
