### ISSUE TITLE
Peggy V2: Atoms on Uniswap

### ISSUE THREAD

**Issue by jtremback** [althea-net/cosmos-gravity-bridge#147]
This is a tracking issue for some enhancements to Peggy which will allow it to bridge tokens originating on Cosmos over to Ethereum (Peggy currently only bridges ERC20 tokens which originated on Ethereum).

Ethereum side:

- There must be an ERC20 contract representing each Cosmos token supported by Peggy.
- This ERC20 must be under the control of the Peggy.sol contract.
- Peggy.sol must be able to give these tokens to users when they send Cosmos tokens to the Peggy Cosmos module.
- Peggy.sol must be able to take these tokens back and fire events to let the Cosmos module give the user Cosmos tokens when going the other direction.

Some other bridges use a pattern where their Ethereum contract is able to mint and burn tokens in ERC20 contracts. For simplicity, we will do something different. ERC20 contracts representing Cosmos tokens will simply be initialized with their entire supply given to Peggy.sol. This will allow the normal submitBatch process to be used to send tokens from Cosmos to Ethereum, and the SendToCosmos event to be used to send tokens from Ethereum to Cosmos.

How will we create these ERC20 contracts? In principle, any ERC20 deployed by anyone can be used, as long as it is a non-malicious ERC20 bytycode, and it has 100% of its supply allocated to Peggy.sol. In practice, it will be most convenient to just have Peggy.sol deploy these contracts.

- [x] `deployERC20(cosmosDenom)` method on Peggy.sol: This method will deploy an ERC20 contract forked from OpenZeppelin with a line in the constructor which mints maxuint256 for Peggy.sol. It will then fire an event- "ERC20Deployed" with the cosmos denom and the ERC20 address. This event will be picked up by the Cosmos module.

Cosmos side:

On the Cosmos side, the main piece of added functionality will be the ability for the Cosmos module to lock and unlock tokens. Currently, it just mints and burns them. It burns them in `(k Keeper) AddToOutgoingPool`, when a user sends from Cosmos -> Eth, and it mints them in `(a AttestationHandler) Handle`, when a user sends from Eth -> Cosmos.

- [x] We will need to add code paths to keep tokens locked on Cosmos instead of burning them, and unlocking them instead of minting them. This needs to be expanded out with a lot more design work before we have clear cut tasks, but it may also be convenient to use locking/unlocking for all transactions, and eliminate minting/burning completely. This might reduce the number of code paths.
- [x] We will need to map Cosmos denoms to ERC20 token contracts. This is actually already done for ethereum-originated tokens, and again we may just be able to recycle the same code paths.
- [x] We will need to add some code to the Ethereum oracle to handle the event of a new ERC20 being deployed by Peggy.sol and associate it to the correct Cosmos denom.

**Comment by jtremback** [comment]
Round trip of a Cosmos-originated asset:

### ERC20 deployment
- Someone calls `deployERC20('uatom')` on Peggy.sol. Peggy.sol deploys an OpenZeppelin ERC20 contract with the entire supply granted to Peggy.sol.
- Peggy.sol fires a `ERC20Deployed` event containing the address of the new ERC20 and the Cosmos denom.
- The Ethereum oracle part of the Peggy module picks up this event and creates an entry in an index mapping ERC20 contract addresses to Cosmos denoms. (I'm a bit fuzzy on the details here, would love some input)

### Cosmos -> Eth
- Alice sends a `MsgSendToEth2` (better name TBD) with an amount of Atoms to transfer and a fee. When the Peggy module receives this message, it transfers the coins into its wallet with `k.bankKeeper.SendCoinsFromAccountToModule`. Notably, different from the current `MsgSendToEth` handler, the coins are not burned, just kept by the module.
- The transaction goes into a batch as normal
- Peggy.sol executes this batch normally, and transfers the ERC20 tokens to the destination. These tokens are given value by the fact that they can be redeemed for tokens on the Cosmos chain.

### Eth -> Cosmos
- Bob calls `sendToCosmos` on Peggy.sol, the same as normal.
- The ERC20 tokens are locked in Peggy.sol and an event is fired.
- The Cosmos module's Ethereum oracle picks up this event, checks which Cosmos denom is associated to the ERC20 contract in the index, and unlocks some Cosmos tokens for Bob.

**Comment by jtremback** [comment]
Almost done! https://github.com/althea-net/cosmos-gravity-bridge/pull/224

**Comment by jkilpatr** [comment]
this is now complete.
