### ISSUE TITLE
Oracle event to relay only block height

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/cosmos-gravity-bridge#169]
As called out in #168 batches will not finish timing out until the block height is updated from the Ethereum side and the entire validator set votes on the claim.

This means that if a batch times out but the bridge is totally inactive the funds will not actually be released to the user until any event occurs on the bridge and brings over an up to date block height.

This isn't a security issue but it's going to be very inconvenient for some users. Especially ones that don't know that sending even the smallest amount of any ERC20 to the bridge will get their batch unlocked.

Ideally we could add another claim event that periodically had the entire validator set vote on the latest Ethereum block height.

**Comment by jtremback** [comment]
We could add a feature that calls `sendToCosmos` with an infinitesimal amount of tokens to trigger timeouts, but that's outside of the scope of this issue, and won't be done soon anyway.
