### ISSUE TITLE
Block Timeouts using timestamps

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/cosmos-gravity-bridge#170]
This is a research issue for designing batch timeouts that make use of the Ethereum block timestamp to better track clock time.

There are some decent resources on [stack exchange](https://ethereum.stackexchange.com/questions/413/can-a-contract-safely-rely-on-block-timestamp) that rule out using timestamp over short periods (a few minutes) but for our use case the minimum batch timeout can be at least a few hours.

1) while the timestamp must increase, it doesn't have to match up with the present. Miners can increase the timestamp by a 1ms every block and have it be valid
2) timestamps can be from the future but not 'too far' how far is determined by the implementation.

This means time can continuously run slower on Ethereum for arbitrarily long times until some miner decides to be honest and re-syncs it with reality. Since this just delays the timeout I don't think it's much worse than slow mining due to a difficulty bomb or a big miner leaving the set.

No matter what though we still need #169 or it's timestamp equivalent. Nothing we can do will allow us to simply release funds without relaying an event from Ethereum first. There's also no way to rule out arbitrary delay from the Ethereum side (although we could maybe reduce it's impact). With those two tradeoffs in mind I don't believe using timestamps will pan out to be *that* much better.

**Comment by jtremback** [comment]
> No matter what though we still need #169 or it's timestamp equivalent. Nothing we can do will allow us to simply release funds without relaying an event from Ethereum first. There's also no way to rule out arbitrary delay from the Ethereum side (although we could maybe reduce it's impact). With those two tradeoffs in mind I don't believe using timestamps will pan out to be that much better.

I disagree with this. I think an analysis that can bound possible timestamp spoofing to some range with enough confidence could allow us to time out batches without relaying timestamps. IMO this is the same dynamic as our ethBlockDelay parameter.

**Comment by jkilpatr** [comment]
> I disagree with this. I think an analysis that can bound possible timestamp spoofing to some range with enough confidence could allow us to time out batches without relaying timestamps. IMO this is the same dynamic as our ethBlockDelay parameter.

I should clarify my position, as long as we insist on 100% certainty that no double spend can occur no matter the miner makeup on Ethereum then it's not possible. 

We may be able to make some assumptions about honest versus dishonest miners.

For example if we want to assume at least one honest miner mines a block in a day then we can release funds based on a clock after 24 hours. But what about a difficulty bomb? That means we need 48 hours. 

Any bets we make about the Ethereum miner makeup must hold true for years on end, not just the present. This makes me rather nervous.
