### ISSUE TITLE
Rename peggy module and binaries

### ISSUE THREAD

**Issue by fedekunze** [althea-net/cosmos-gravity-bridge#185]
Consider renaming the peggy module to gravity or eth_bridge and the binary to `gravityd`

**Comment by jtremback** [comment]
Also, consider renaming the "Orchestrator" to "Relayer" and "Eth Signer"

**Comment by fedekunze** [comment]
yesss please

**Comment by jtremback** [comment]
This is a giant pain in the ass and we have to do it once there are no other features outstanding because otherwise it will be the mother of all merge conflicts

**Comment by marbar3778** [comment]
I can take this on. Will open a PR latter today.
