### ISSUE TITLE
Remaining tasks for a production ready Gravity

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/cosmos-gravity-bridge#193]
# Spam

- [x] Limit number of outstanding batches to 5 per token type. to prevent using batch signatures as a spam transaction amplifier
- [x] Implement rules requiring a new batch to be more profitable than the previous one. 

# Slashing

- [x] Slashing for lost delegate keys (mostly to force rotation)
- [x] Slashing for evidence of Ethereum signature that isn't from the Cosmos chain (heavy slashing, indicates attempted bridge takeover) (Audit bugs s1 and s2)
- [x] Valsets should have a height that is used for slashing, independent of the nonce value

# Messages
- [ ] Retrieving the latest batches and logic calls to sign should use an array (like valsets now do) to ensure faster signing

# State cleanup

- [x]  Valsets need to be cleaned up from state eventually. I think no sooner than 6 months after their creation

# Relayer

- [x] Configurable ability to not submit batches less than x% profitible
- [x] Relayer should auto-navigate uniswap to determine the price of a given erc20 and thus fee value
- [x] Relayer should be able to auto-liquidate earned ERC20 tokens to continue to fund operations
- [x] Investigate and fix cost estimate failed messages
- [ ] Prevent gas-wasting 10 car pileup of message submission. 

# Arbitrary Logic

- [ ] tests
- [ ] add tx type to let regular users use arbitrary logic calls?

# Technical Debt

- [x] Reduce spurious failures in the integration tests
- [x] Proto transactions for the orchestrator
- [ ] Reduce integration test runtime on osX platforms by removing docker
- [x] Rename Peggy module and binaries once activity dies down, or face the mother of all merge conflicts (#185)
- [ ] Confirmations should be stored by orchestrator key (issue #195 )
- [ ] Store needs to be cleaned up and getters should always return nil when the item isn't present

**Comment by albertchon** [comment]
> Slashing for evidence of Ethereum signature that isn't from the Cosmos chain (heavy slashing, indicates attempted bridge takeover) (Audit bugs s1 and s2)

So the orchestrator can never transfer use any private key that he used for the `EthAddress` ever again? 

If that's not the case (e.g. only for the current active EthAddress), the takeover attempting person could just set `MsgSetOrchestratorAddress` with a different `EthAddress` after his takeover attempt fails. Not sure if that's what you're referencing here https://github.com/althea-net/cosmos-gravity-bridge/blob/82dd536d7ce2f7ba5a222eef88a8bd8fab14bd3d/module/x/peggy/keeper/msg_server.go#L43

Is there more info/a canonical aggregated doc with all of the Audit bugs? @jkilpatr

**Comment by jkilpatr** [comment]
> So the orchestrator can never transfer use any private key that he used for the `EthAddress` ever again?

we should probably just limit to a signed Valset update that was not produced by the Cosmos chain. Although requiring a throw-away Ethereum address isn't exactly a high bar it's good to be more specific. 

> Is there more info/a canonical aggregated doc with all of the Audit bugs? @jkilpatr


It's in my email, having a meeting with the auditors in a few minutes. They have opened issues for everything now I think but we want to go back and forth over the doc one more time before finalizing it.

**Comment by albertchon** [comment]
We should also add:
- adding export state and import state into the CI 
- creating a sound plan/procedure on how to properly restart the chain in the event of a consensus failure that's compatible with the Peggy model

**Comment by jkilpatr** [comment]
@albertchon 

good points.

1) state import/export is in master right now. You need a alchemy API key to use it but it does work.

2) as for how to properly restart the chain we've done this twice on Althea testnet now you just restart the chain and make sure that everyone is running their orchestrators. I don't really see more complexity to it than that. What you *can't* do is play back the validator state too far that it will be out of sync with the bridge. You must resume the chain at the same height and with the same set you stopped at.

**Comment by jkilpatr** [comment]
A few of these issues are still open, but I'm closing this as mostly out of date.
