### ISSUE TITLE
No Trusting Period Check in Ethereum

### ISSUE THREAD

**Issue by josef-widder** [althea-net/cosmos-gravity-bridge#200]
Surfaced from [Informal Systems](https://informal.systems/) Gravity Bridge Audit of https://github.com/cosmos/gravity-bridge/commit/df4f1fb4f38d008165760b169637862966d40bb4.

The Tendermint security model induces a trusting period that ensures that validators with more than 2/3 of the voting power that signed the block are correct during the trusting period. In other words, after the trusting period expires, it must be assumed that validators behave arbitrary.

The Solidity contract does not check this trusting period. It does not record when the `checkpoint` has been updated the last time. As a result, it cannot be checked in the contract whether the trusting period has passed since the last update.

### Problem Scenarios

No update of the `checkpoint` happens for more than the trusting period.
- this can be because validators do not sign (for this they are slashed in the CosmosSDK module)
- it may be that a relayer does not manage to get the ValSetUpdate on Ethereum (e.g., because transaction fees are currently too high, connection is lost, etc.)

As a result, the current `checkpoint` on the Solidity side may be disconnected from the current bonded and unbonding validators on the Cosmos side. At the same time, the Solidity smart contract is totally controlled by the validators in the `checkpoint`, that is, they may submit arbitrary batches of transactions and thus collect all the funds stored in the contract.

### Recommendation

IBC addresses this problem as follows:

- validation is based on Tendermint light blocks
- lightblock validation checks the trusting period
- if there are no new lightblocks installed within the duration of the trusting period, then no new lightblocks can be installed
- in this case, effectively, the light client halts.

This could be addressed by implementing a check for the age of the current `checkpoint`. Alternatively, the design choice should be made explicit in the documentation.

**Comment by jtremback** [comment]
I believe this has been resolved by adding this language in README.md:

> There must be a validator set update made on the Ethereum contract by calling the updateValset method at least once every Cosmos unbonding period (usually 2 weeks). This is because if there has not been an update for longer than the unbonding period, the validator set stored by the Ethereum contract could contain validators who cannot be slashed for misbehavior.

We will not be implementing the timeout, because it turns a possible loss of funds (from theft) after the unbonding period is up into a guaranteed loss of funds (from the bridge locking).

This should be closed once it's reviewed by Informal.

**Comment by jkilpatr** [comment]
Closing pending next audit round.
