### ISSUE TITLE
Slashing and Obligations during Unbonding

### ISSUE THREAD

**Issue by josef-widder** [althea-net/cosmos-gravity-bridge#201]
Surfaced from [Informal Systems](https://informal.systems/) Gravity Bridge Audit of https://github.com/cosmos/gravity-bridge/commit/df4f1fb4f38d008165760b169637862966d40bb4.

In Tendermint, correct behavior of validators in incentivized by slashing for misbehavior. However, in Tendermint, if a validator leaves the active validator set, and starts unbonding, it will not be punished for not signing new messages. However, since the bridge manages the `checkpoint` on the application level, it is required that unbonding validators sign new checkpoints. Similarly, until the `checkpoint` is updated at the Solidity contract, the validators in the old checkpoint may need to sign batches.

Thus the current design tries to enforce liveness by slashing unbonding validators for not signing data even after they left the Tendermint validator set.

On the contrary, many types of lying is not slashable in the current design: If validators sign and submit a bogus `checkpoint` or a bogus batch to the Solidity contract this has no consequences.

### Problem Scenarios

There are some economic scenarios that open up by such a rule:

- Issuing RequestBatch may create many batches and force (due to slashing conditions) unbonding validators to sign and submit the signed batches to Tendermint. In case transaction fees are involved with such signatures, the bonded validators may earn from that, and may have the incentive to generate many batches.

- The same question arises for ValSetUpdate.

- It seems that the slashing code only looks for bonded but not for unbonding validators (contrary to the code comments).

### Recommendation

1. Clarify the slashing specification: bonding vs. unbonding.

2. Check whether the intended validator sets are queried from the staking module.

3. Clarify the economics of the slashing conditions (signing cost vs. cost of being slashed).

4. Add slashing rules for provable lying.

**Comment by jtremback** [comment]
This is discussed in #216 #217 #218.

The tx fee part of this issue can be solved by making valset signature submission from validators and former unbonding validators free.

We are working to reduce the time period for which unbonding validators need to keep signing. Right now we think we can get it down to 24 hours. It could theoretically be possible to allow them to sign only one more thing, a "valset leaving" tx, but that would require a lot of code changes in the module and the contract.

**Comment by marbar3778** [comment]
This seems like something epoched staking would help with. At the end of the epoch-1 you can update the validator sets throughout the system instead of allowing this on a per block basis.

**Comment by jkilpatr** [comment]
I believe this is now well described in this document

https://github.com/althea-net/cosmos-gravity-bridge/blob/main/spec/slashing-spec.md

If there are any remaining questions feel free to re-open the issue.
