### ISSUE TITLE
Possible Loss of User Funds on Unsuccessful Transfers

### ISSUE THREAD

**Issue by josef-widder** [althea-net/cosmos-gravity-bridge#202]
Surfaced from [Informal Systems](https://informal.systems/) Gravity Bridge Audit of https://github.com/cosmos/gravity-bridge/commit/df4f1fb4f38d008165760b169637862966d40bb4.

- On the Ethereum side, `SendToCosmos` transfers the funds to the Solidity contract and sends a transaction to Cosmos. However, there is no timeout on that transaction. If the transfer is not successful, there is no way the sender can get their money back.

- On the Cosmos side, `SendToEth` puts a transaction into the `OutgoingTXPool` and withdraws the money from the senders account. If the transaction starves in the pool, there is no way the sender can get their money back.

### Problem Scenarios

On the Ethereum side, this might only happen in an extreme case, as all events are handled on the Cosmos side in order, that is, as long as the bridge keeps operating, the transaction might go through. (Still it is unclear why there are timeouts in terms of batches in the other direction, but no timeouts in this direction).

On the Cosmos side this appears more of an issue, as the batch selection logic, and the way transactions in batches that are overtaken are returned to the  `OutgoingTXPool` it appears that returning funds to Ethereum might suffer from starvation.

### Recommendation

Implement timeouts in the interface facing the users.

**Comment by jtremback** [comment]
This is a minor feature that still needs to be added, we need some boilerplate endpoints allowing users to take their tx's out of the tx pool (not the batch pool!) and refund them.
