### ISSUE TITLE
Potential Masquerading Attack

### ISSUE THREAD

**Issue by josef-widder** [althea-net/cosmos-gravity-bridge#203]
Surfaced from [Informal Systems](https://informal.systems/) Gravity Bridge Audit of https://github.com/cosmos/gravity-bridge/commit/df4f1fb4f38d008165760b169637862966d40bb4.

The message handlers

- `SetOrchestratorAddress`
- `DepositClaim`
- `WithdrawClaim`

work on unsigned data. 

### Problem Scenarios

Anyone who knows the orchestrator address may vote on its behalf. This may result in severe attacks (bogus money movements).

### Recommendation

1. Require this data to be signed by the orchestrator.

2. Check the signatures in the module.

**Comment by jtremback** [comment]
This is a minor implementation oversight, we need to check those signatures.

**Comment by jkilpatr** [comment]
all claims implement getSigners in this format. Therefore the orchestrator must sign. Or this code doesn't do what I think it does. 

Likewise the set orchestrator address has a similar block for the validator key. 

```
// GetSigners defines whose signature is required
func (msg MsgERC20DeployedClaim) GetSigners() []sdk.AccAddress {
	acc, err := sdk.AccAddressFromBech32(msg.Orchestrator)
	if err != nil {
		panic(err)
	}

	return []sdk.AccAddress{acc}
}
```
