### ISSUE TITLE
Possible Liveness Violation on Batch Confirm

### ISSUE THREAD

**Issue by josef-widder** [althea-net/cosmos-gravity-bridge#204]
Surfaced from [Informal Systems](https://informal.systems/) Gravity Bridge Audit of https://github.com/cosmos/gravity-bridge/commit/df4f1fb4f38d008165760b169637862966d40bb4.

In the current code of `ConfirmBatch`, an Orchestrator needs to be in the current validator set **AND** in the checkpoint in order to pass all the checks. 

### Problem Scenarios

If a validator is in the checkpoint but not in the validator set, its confirmation will not be recorded. However, its signature may be needed in the Solidity contract. As a result liveness may be violated.

### Recommendation

Remove the check whether the orchestrator is in the validator set and only check whether it is in the `checkpoint`.

**Comment by jtremback** [comment]
Just some clarification needed here, @josef-widder, and this doesn't have anything to do with the main issue.

> AND in the checkpoint in order to pass all the checks

Are you saying that we check whether a validator calling this method is in the validator set stored in the Ethereum contract? Because we are not doing this. The Cosmos module does not know which validators are in the Ethereum contract's checkpoint at any given time. It is up to the relayer to choose those signatures which are necessary.

**Comment by jtremback** [comment]
As for the main issue raised, it appears that we may be checking that the message signer is a validator. What we need to do is check whether the message signer is a validator OR an unbonding former validator.

**Comment by jkilpatr** [comment]
In the current code anyone can submit a confirm, so long as they have a valid orchestrator address. Anyone who has ever been a validator for any period of time must have set an orchestrator address during that period.

This may be a spam attack. But the scope has been reduced at least that much.

```
// ConfirmBatch handles MsgConfirmBatch
func (k msgServer) ConfirmBatch(c context.Context, msg *types.MsgConfirmBatch) (*types.MsgConfirmBatchResponse, error) {
	ctx := sdk.UnwrapSDKContext(c)

	// fetch the outgoing batch given the nonce
	batch := k.GetOutgoingTXBatch(ctx, msg.TokenContract, msg.Nonce)
	if batch == nil {
		return nil, sdkerrors.Wrap(types.ErrInvalid, "couldn't find batch")
	}

	peggyID := k.GetPeggyID(ctx)
	checkpoint, err := batch.GetCheckpoint(peggyID)
	if err != nil {
		return nil, sdkerrors.Wrap(types.ErrInvalid, "checkpoint generation")
	}

	sigBytes, err := hex.DecodeString(msg.Signature)
	if err != nil {
		return nil, sdkerrors.Wrap(types.ErrInvalid, "signature decoding")
	}

	orchaddr, _ := sdk.AccAddressFromBech32(msg.Orchestrator)
	validator := k.GetOrchestratorValidator(ctx, orchaddr)
	if validator == nil {
		return nil, sdkerrors.Wrap(types.ErrUnknown, "validator")
	}

	ethAddress := k.GetEthAddress(ctx, validator)
	if ethAddress == "" {
		return nil, sdkerrors.Wrap(types.ErrEmpty, "eth address")
	}

	err = types.ValidateEthereumSignature(checkpoint, sigBytes, ethAddress)
	if err != nil {
		return nil, sdkerrors.Wrap(types.ErrInvalid, fmt.Sprintf("signature verification failed expected sig by %s with peggy-id %s with checkpoint %s found %s", ethAddress, peggyID, hex.EncodeToString(checkpoint), msg.Signature))
	}

	// check if we already have this confirm
	if k.GetBatchConfirm(ctx, msg.Nonce, msg.TokenContract, orchaddr) != nil {
		return nil, sdkerrors.Wrap(types.ErrDuplicate, "duplicate signature")
	}
	key := k.SetBatchConfirm(ctx, msg)

	ctx.EventManager().EmitEvent(
		sdk.NewEvent(
			sdk.EventTypeMessage,
			sdk.NewAttribute(sdk.AttributeKeyModule, msg.Type()),
			sdk.NewAttribute(types.AttributeKeyBatchConfirmKey, string(key)),
		),
	)

	return nil, nil
}
```
