### ISSUE TITLE
ValSetConfirm EthAddress redundant

### ISSUE THREAD

**Issue by josef-widder** [althea-net/cosmos-gravity-bridge#208]
Surfaced from [Informal Systems](https://informal.systems/) Gravity Bridge Audit of https://github.com/cosmos/gravity-bridge/commit/df4f1fb4f38d008165760b169637862966d40bb4.

The [message type](https://github.com/cosmos/gravity-bridge/blob/df4f1fb4f38d008165760b169637862966d40bb4/module/x/peggy/types/msgs.pb.go#L158) contains `EthAddress` while the message [handler](https://github.com/cosmos/gravity-bridge/blob/df4f1fb4f38d008165760b169637862966d40bb4/module/x/peggy/keeper/msg_server.go#L66) does not use the field but looks up the `EthAddress` for the validator from the store. I guess the field can be removed from the message (or should be validated in the code).

**Comment by jtremback** [comment]
This field is useful for the relayer so it should not be removed.

**Comment by jkilpatr** [comment]
we could potentially have an endpoint that would let us request everyone' ethereum keys by validator key (in fact we do have such an endpoint now) but it's kinda awkward when we can just include on field of metadata and save a request.
