### ISSUE TITLE
Valset request sent for each SignedValsetsWindow even if power < 5%

### ISSUE THREAD

**Issue by mankenavenkatesh** [althea-net/cosmos-gravity-bridge#217]
According to below logic, `ValsetRequest` is sent whenever len(valsets) == 0.

https://github.com/althea-net/cosmos-gravity-bridge/blob/82dd536d7ce2f7ba5a222eef88a8bd8fab14bd3d/module/x/peggy/abci.go#L25

**Problem:**
As valset is pruned for every `SignedValsetsWindow`, 
len(valsets) == 0 for every `SignedValsetsWindow`
resulting in sending `ValsetRequest` though powerDiff < 5%

**Comment by jkilpatr** [comment]
This is a good catch, although I would say there should always be an available valset to realy. But that should be solved by expanding the window before deletion in #218
