### ISSUE TITLE
command line:  orchestrator -h and orchestrator --help return Invalid arguments.

### ISSUE THREAD

**Issue by xela7** [althea-net/cosmos-gravity-bridge#240]
orchestrator -h and orchestrator --help return Invalid arguments instead of just returning help.

For example:

$ orchestrator -h
Invalid arguments.

Usage: orchestrator --cosmos-phrase=<key> --ethereum-key=<key> --cosmos-legacy-rpc=<url> --cosmos-grpc=<url> --ethereum-rpc=<url> --fees=<denom> --contract-address=<addr>
        Options:
            -h --help                    Show this screen.
            --cosmos-key=<ckey>          The Cosmos private key of the validator
            --ethereum-key=<ekey>        The Ethereum private key of the validator
            --cosmos-legacy-rpc=<curl>   The Cosmos RPC url, usually the validator
            --cosmos-grpc=<gurl>         The Cosmos gRPC url, usually the validator
            --ethereum-rpc=<eurl>        The Ethereum RPC url, should be a self hosted node
            --fees=<denom>               The Cosmos Denom in which to pay Cosmos chain fees
            --contract-address=<addr>    The Ethereum contract address for Peggy, this is temporary
        About:
            The Validator companion binary for Peggy. This must be run by all Peggy chain validators
            and is a mix of a relayer + oracle + ethereum signing infrastructure
            Written By: Justin Kilpatrick <justin@althea.net>
            Version 0.4.1

**Comment by jkilpatr** [comment]
Thanks for the report! I believe this issue is solved in the current main branch
