### ISSUE TITLE
Modify prefix to account for the potential of having multiple gravity instances on one chain

### ISSUE THREAD

**Issue by jackzampolin** [althea-net/cosmos-gravity-bridge#246]
We should modify the denom prefix for tokens moved over to peggy potentially by making the string configurable in `app.go`. This helps in the case were a chain is running multiple instances of the peggy module and bridging say BSC and ETH mainnet.

**Comment by jkilpatr** [comment]
this is a reasonable ask I think. We generally need to evaluate the entire 'multiple instances' usecase, since it will require the exteranl programs like the orchestrator keep track of multiple modules at once.

**Comment by jkilpatr** [comment]
Coming back to this after a long time, I believe this is just part of a much larger series of changes required to make multiple Gravity instances functional at the same time on the same chain. Probably best to fold that into one issue for the sake of organization.

**Comment by jkilpatr** [comment]
Closing to try and reduce the size of the issues list, this issue can be used to coordinate all the design difficulties of running multiple instances of Gravity 

https://github.com/althea-net/cosmos-gravity-bridge/issues/293
