### ISSUE TITLE
Make Key delegation able to be run in `gentx`s 

### ISSUE THREAD

**Issue by jackzampolin** [althea-net/cosmos-gravity-bridge#248]
Ideally we get validators to submit an ETH key delegation message for inclusion in genesis so that the chain starts with all validators having an ETH key delegated.

**Comment by jkilpatr** [comment]
+1 to this. If this was the case then we could start the chain with the Gravity contract already deployed.

**Comment by jkilpatr** [comment]
This is completed and in current gentx's
