### ISSUE TITLE
core: migrate development to cosmos repo

### ISSUE THREAD

**Issue by marbar3778** [althea-net/cosmos-gravity-bridge#253]
## Summary

Discussed with Jack and Justin, it was mentioned moving from althea fork of the gravity bridge to the cosmos repo is doable. 

We should try to merge the outstanding PRs and then migrate there. There will be a minor issue with issues, but for the time being would it be okay to work across to repos for now?

**Comment by jkilpatr** [comment]
this is mostly done, finishing a few issues here
