### ISSUE TITLE
Attack Scenario - Mint extra Deposit Amount 

### ISSUE THREAD

**Issue by mankenavenkatesh** [althea-net/cosmos-gravity-bridge#269]
**Context**
During DepositClaim processing, Attestation is created with 
```
key = (EventNonce + ClaimHash) 
where ClaimHash = is concatenation of (TokenContract + EthereumSender + CosmosReceiver)
```
&

```
Value =  &types.Attestation{
			Observed: false,
			Height:   uint64(ctx.BlockHeight()),
			Claim:    anyClaim,
		}
anyClaim, err := codectypes.NewAnyWithValue(msg)
```

**Problem:**
Let's say there is a Deposit event on Ethereum gravity contract with userA depositing **100 INJ** tokens.

Assume one of the validator is malicious. He created a `MsgDepositClaim` with Deposit Amount = **200 INJ** tokens and broadcasted this msg to peggy. Peggy module creates Attestation for the first time embedding MsgDepositClaim with Deposit Amount = **200 INJ**  tokens.

Even though next set of validators broadcasts `MsgDepositClaim` with **100 INJ tokens (correct amount)**, we are just fetching previous attestation as (EventNonce + ClaimHash) matches and adding validator addr into votes.
https://github.com/althea-net/cosmos-gravity-bridge/blob/5b17e1a29e6ca78e8382603ae8bd971d3c218f36/module/x/gravity/keeper/attestation.go#L35

In Endblocker, when attestation tally happens, as 2/3+1 has voted, the attestation will go through and mints 200 INJ tokens.

So Malicious validator is able to mint extra tokens as **we don't evaluate the deposit amount anywhere** in the flow.

**Solution**

ClaimHash should be concatenation of (TokenContract + EthereumSender + CosmosReceiver + **DepositAmount**)

**Comment by mankenavenkatesh** [comment]
I think we should add EventNonce also as 
Malicious validator can change the eventNonce to huge value thus halting the deposits completely.

**Solution**
ClaimHash should be concatenation of (TokenContract + EthereumSender + CosmosReceiver + **DepositAmount** + **EventNonce**)

**Comment by jkilpatr** [comment]
Hey @mankenavenkatesh  thanks a lot for reporting this. Working on a patch right now.
