### ISSUE TITLE
Valset Nonce is not sequential. 

### ISSUE THREAD

**Issue by mankenavenkatesh** [althea-net/cosmos-gravity-bridge#279]
**Context**
Recently there is a new commit to Implement Sequential Valset nonces.

Reference - https://github.com/althea-net/cosmos-gravity-bridge/commit/4adc8d10e5814264a4bf03944aebf9ea757e9f28

In Endblocer, a new valset request is created through these sequence of function calls.   
`SetValsetRequest() -> GetCurrentValset() -> StoreValset()`

where `GetCurrentValset()` calls `IncrementLatestValsetNonce()` which fetches `LatestValsetNonce`, increments it and persist to store. 

The incremented valset nonce is used to create the ValsetRequest.

**Problem**
 `GetCurrentValset()` function is called from multiple places.
  
 1. when checking PowerDiff in abci.go
 https://github.com/althea-net/cosmos-gravity-bridge/blob/ba1ccadfdd677f96a647b463813f444fad032df3/module/x/gravity/abci.go#L36
 
 2. Grpc query to fetch current valset
 https://github.com/althea-net/cosmos-gravity-bridge/blob/ba1ccadfdd677f96a647b463813f444fad032df3/module/x/gravity/keeper/grpc_query.go#L26
 
 3. Querier
 https://github.com/althea-net/cosmos-gravity-bridge/blob/ba1ccadfdd677f96a647b463813f444fad032df3/module/x/gravity/keeper/querier.go#L279
 
 
As the LatestValsetNonce can be incremented from each of these Get calls, the ValsetRequests created won't have nonce in sequential order.

**Solution**
It's not a Good practice to update the state in Get Calls. 
Increment the Latest Valset Nonce only when Valset is created.

**Comment by jkilpatr** [comment]
Thanks for reporting this, you're correct about the issue, the current implementation will skip valset nonces due to this issue.
