### ISSUE TITLE
Ensure that MsgSendToEth transactions enter the gensis state

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/cosmos-gravity-bridge#322]
This issue is to write a unit test that sends a MsgSendToEth and then checks the genesis exporting function to ensure that it contains that message.

https://github.com/althea-net/cosmos-gravity-bridge/blob/main/module/x/gravity/keeper/genesis.go#L151

https://github.com/althea-net/cosmos-gravity-bridge/blob/main/module/x/gravity/keeper/msg_server.go#L111

You really only need these two functions in the unit test. In fact an existing unit test for MsgSendToEth could probably be reused.

**Comment by ChristianBorst** [comment]
Created https://github.com/althea-net/cosmos-gravity-bridge/pull/324 to resolve this.

My test creates 4 unbatched transactions and makes sure they all appear in the export data
