### ISSUE TITLE
Determine what needs to be persisted for a valid genesis state

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/cosmos-gravity-bridge#64]
This issue is for us to enumerate all the state we need to store in order to have the bridge properly deal with chain upgrades. 

The most confusing part of this is probably #61 and it may be required that we resolve that issue fully before we can properly enumerate what goes here.

* Valset nonce
* TX batch nonce
* Nonces for each Oracle event? (see #61)
* The validator state corresponding to the current valset nonce (should be one struct in the store?)
* The delegated Eth addresses of every validator and once implemented the delegated Cosmos address
* The bridge mempool so that transactions don't get lost with no way to refund.

**Comment by alpe** [comment]
We have the following data so far:
* [ ] EthAddressKey
* [ ] Valsets
* [ ] ValsetConfirmations (deprecated by generic bridge signatures)
* [ ] Claims (Observed, "approved")
* [ ] Approval signatures (for Ethereum bridge contract)
* [ ] Attestations
* [ ] Nonces
* [ ] Sequences ("lastTxPoolId", "lastBatchId")
* [ ] BridgedDenominators
* [ ] Outgoing TX (Withdrawals)
* [ ] Outgoing Batches (Withdrawals)
* [ ] Second indexes (UnbatchedTXByFee, NonceByClaimKey)
* [ ] Params

**Comment by jkilpatr** [comment]
@alpe  can you clarity what you mean by 'second indexes'? What are those used for in the code. 

Other than that question I think this is complete and should be worked on after the stargate upgrade.

**Comment by jtremback** [comment]
I think this is done
