### ISSUE TITLE
How to make the most profitable batch possible

### ISSUE THREAD

**Issue by jtremback** [althea-net/cosmos-gravity-bridge#90]
Batch profitability for a relayer is determined by `sum(txFees) - totalEthGasCost`.

We don't know the eth gas cost, so we can't directly use the equation on the first line. Knowing this would require two pieces of information: the current gas cost on Ethereum in Eth, and the price of the token in question (to be able to relate the costs to each other). Getting the current gas cost could be done without too much trouble, but getting the price of every random token on Ethereum seems troublesome. We could use a price feed from something like Uniswap, but this would open us up to a universe of cryptoeconomic DeFi attacks from people influencing the exchange rate.

1. Taking the average fee per transaction (`sum(txFees) / numTxs`) seems like it could work, but only if every batch has the same number of transactions. If every batch did not have the same number of transactions, then the "most profitable" batch according to this equation would only have one transaction. This would not actually be the most profitable. We don't want every batch to have the same number of transactions because this would force the inclusion of unprofitable transactions. For example, if every batch needed to have 100 transactions, and the tx pool had 70 spam transactions and 30 profitable transactions, then it would likely never be profitable to submit the batch, even if the 30 transactions would have been profitable without the spam.

2. We could use `sum(txFees)`, but this would also force the inclusion of unprofitable transactions. The batch with 30 profitable and 70 spam transactions would be slightly more profitable according to this equation than the 30 profitable transactions alone, even though this was not really the case. 

3. We could use a scaled average `sum(txFees) / (numTxs * alpha)`. This is a tradeoff between the two previous equations, with the amount of tradeoff adjustable by the constant `alpha`. I'm not sure how we would go about setting this constant and how well it would actually work.

**Comment by jtremback** [comment]
My vote is to go with 2 if we can't think of anything better, even though the spam transactions could cause throughput problems. 

The procedure to create the most profitable batch according to 2 would be to order all transactions from low to high fees and take the `n` highest fee transactions. I believe the code may do this now.

One caveat with this approach is that a fixed number of transactions per batch does impose a gas cost limit on the ERC20's that Peggy can work with. An ERC20 with very expensive transactions could exceed the block gas limit.

**Comment by jtremback** [comment]
After a discussion with @jkilpatr this morning, we've come to the conclusion that the naive batch construction implied by 2 is already being done in the code written by @alpe.

And to take note of a possible mitigation of the disadvantages of this technique, one idea would be to have the batch size dynamic. 

In a scenario where there were 60 profitable transactions and 40 spam transactions with a batch size of 100, resulting in the batch not being profitable, the batch sized could be reduced after the batch not getting in for a time, until it was small enough that the 60 profitable transactions outweighed the spam transactions, e.g. 60 profitable transactions and 10 spam transactions, with a batch size of 70. 

However, this would require some pretty big changes in how the rest of it works, including having batches expire so that those profitable transactions could be released to be used in a new, possibly profitable batch.

**Comment by alpe** [comment]
This is a good discussion.
In the current design the orchestrator would trigger a batch request. The result would be the list of transactions as described in version 2). I would be up to the orchestrators to decide if this batch should be submitted or not.
There can be reasons to submit unprofitable batches, for example to guarantee a throughput. I would expect different peg zones to build their own business processes here.

Some options/ideas to tweak the batch building with version 2):
* The orchestrator could pass the max TX limit with the batch building request
* The orchestrator could pass a minimal fee for a TX that would go into a batch with the batch building request
* TX would be canceled and removed from the queue automatically when timeout, lower than fee x, gov proposal,... ???

**Comment by jtremback** [comment]
Good analysis of the issues in here (if i do say so myself), but we will shelve this now and revisit once we have real operational experience.
