### ISSUE TITLE
Community feature discussion for Peggy

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/cosmos-gravity-bridge#91]
As we come up on our September Peggy V1 milestone we would like to ask the Cosmos community what custom features they envision for Peggy on their zone.

If enough separate zones are interested in the same feature obviously it's a good candidate to for cooperation and upstream consideration.

It's also possible that several zones will be interested in custom features with common themes, take special transaction fee rules for example, cooperation to create a single interface could make these modifications for each chain significantly easier.

Please provide feedback!

**Comment by jtremback** [comment]
It might be good to have some functionality on the Eth side where Peggy can not only send tokens to someone's account, but also call arbitrary functions for them. 

The use case here would be, for example, having Peggy call into Uniswap to do a bridge from Cosmos and a swap into another token in one step. This is something that would be useful for Althea routers, who now have to do several steps in a slowish and error prone process.

**Comment by jtremback** [comment]
We did this, serving the community. Thanks for the suggestion @jtremback !
